
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rayrfitltjfymcngveiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJheXJmaXRsdGpmeW1jbmd2ZWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMTk4NDMsImV4cCI6MjA1Nzc5NTg0M30.GUzaIk0WUy0N6JZjfA-fMJiYsmhENpc-N87babqf8_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper functions for email and SMS services that interact with Supabase Edge Functions
export const sendEmailVerification = async (userId: string, email: string) => {
  try {
    const redirectUrl = `${window.location.origin}/verify-email`;
    const { data, error } = await supabase.functions.invoke("send-email-verification", {
      body: { userId, email, redirectUrl, type: "verification" },
    });
    
    if (error) throw error;
    return data;
  } catch (error) {
    console.error("Error sending email verification:", error);
    throw error;
  }
};

export const sendWelcomeEmail = async (userId: string, email: string, fullName: string) => {
  try {
    const { data, error } = await supabase.functions.invoke("send-email-verification", {
      body: { userId, email, type: "welcome", fullName },
    });
    
    if (error) throw error;
    return data;
  } catch (error) {
    console.error("Error sending welcome email:", error);
    throw error;
  }
};

export const sendSMSVerification = async (userId: string, phone: string) => {
  try {
    const { data, error } = await supabase.functions.invoke("send-sms-verification", {
      body: { userId, phone, type: "verification" },
    });
    
    if (error) throw error;
    return data;
  } catch (error) {
    console.error("Error sending SMS verification:", error);
    throw error;
  }
};

export const sendSMSNotification = async (userId: string, phone: string, message: string) => {
  try {
    const { data, error } = await supabase.functions.invoke("send-sms-verification", {
      body: { userId, phone, message, type: "notification" },
    });
    
    if (error) throw error;
    return data;
  } catch (error) {
    console.error("Error sending SMS notification:", error);
    throw error;
  }
};
