// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ummpiutllxtpegzwweme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtbXBpdXRsbHh0cGVnend3ZW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNDI1MzIsImV4cCI6MjA1NzcxODUzMn0.XlLQa0wbB54WQyNWU32uEuVn0CZHQfC7_yAmp8GgqmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);